### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by liveme** [infamous/glas#4]
It make an error when I run `npm install`:
`
npm ERR! code 1
npm ERR! Command failed: git checkout runtime
npm ERR! error: pathspec 'runtime' did not match any file(s) known to git.
`

Using `yarn install` also prompts for failure:
`
error Couldn't find match for "runtime" in "refs/heads/2.4.2,refs/heads/asc_to_devDep,refs/heads/fix_ts_output,refs/heads/greenkeeper/ts-jest-24.1.0,refs/heads/greenkeeper/ts-jest-pin-24.0.2,refs/heads/master,refs/heads/v2.2.1,refs/heads/v2.3.2,refs/heads/v2.3.3,refs/heads/v2.4.1.0,refs/pull/100/head,refs/pull/...
`

**Comment by trusktr** [comment]
Hello! @jtenner, author of [as-pect](as-pect) has since deleted the `runtime` branch from as-pect, which this is depending on in package.json.

By the way, this project doesn't render anything on the screen yet (that's what we're aiming for of course). It currently runs unit tests for the classes we've finished so far. But it would be great if you want to contribute. Thanks for checking it out!

---

@jtenner, would you be open to make a PR to bring this up to date with as-pect from NPM? I'd like to swing back to this soon after some other stuff in my life calms down.

**Comment by jtenner** [comment]
I switched to a mono repo to get more organized about how aspect worked. I could probably help with a pull request if you needed it.

**Comment by trusktr** [comment]
That would be great! I'm sure the changes aren't much, but you'd know best. What was working before was `npm install && npm test`.

**Comment by jtenner** [comment]
This is unfortunate. When I tried to run latest AssemblyScript and latest @as-pect/cli together, I found a compile-time error.

```
ERROR TS2339: Property 'dataLength' does not exist on type '~lib/arraybuffer/ArrayBufferView'.

   if (actual.dataLength != expected.dataLength) {
              ~~~~~~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/comparison/arrayComparison.ts(49,13)

ERROR TS2339: Property 'dataLength' does not exist on type '~lib/arraybuffer/ArrayBufferView'.

   if (actual.dataLength != expected.dataLength) {
                                     ~~~~~~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/comparison/arrayComparison.ts(49,36)
```

This is going to take some time and an update. Sorry for the trouble.

**Comment by trusktr** [comment]
@jtenner Just gave it a shot, and everything is working! Nice! :godmode:

I've [updated assemblyscript and as-pect](https://github.com/infamous/glas/pull/5), and [added continuous integration](https://github.com/infamous/glas/pull/6) (too easy with GitHub Actions). 

Not sure how the build passed though, as the CI pull request doesn't have the updated dependencies. Hmmm, well let me get the first PR merged.

**Comment by trusktr** [comment]
Alright @liveme, it is good to go. `npm install` should work and `npm test` should pass. There's nothing to see yet, but so far 61 unit tests should pass.

If you'd like to grab any class from the Three.js repository along with its unit tests, and port it to AssemblyScript, that'd be awesome.

It'll be some time before it renders anything. The hardest part will be porting over `WebGLRenderer` and making JS glue code so that it can tell the JS (WebGL API) what to render in the DOM `<canvas>` element.

At present, the `WebGLRenderer` class contains the `<canvas>` element, but this is not yet possible in WebAssembly, so instead it will need to contain a render command list, and that list will be passed to the JavaScript side, where the `<canvas>` WebGL context can be accessed.

**Comment by munrocket** [comment]
`npm install` gives an error on macOS 😱 
```
(node:53821) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
```
So I just changed `make-dir dist --mode=0744` to `mkdir dist` in package.json.
